---
- name: Install NGINX on target EC2
  hosts: webserver
  become: yes

  tasks:
    - name: Install NGINX
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start and enable NGINX service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

